name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".vscode/**"
  pull_request:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".vscode/**"
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    name: Check code formatting
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Java Setup
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - name: Check code formatting
        run: mvn git-code-format:validate-code-format --batch-mode
  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Java Setup
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - name: Run tests
        run: mvn test --batch-mode
